# Generated by Django 3.2.2 on 2021-05-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='no found', upload_to=''),
        ),
    ]
