# Generated by Django 3.2.2 on 2021-05-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='comment_by',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='comment_to',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='like_to',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='likeby',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='by_user',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
