# Generated by Django 3.2.2 on 2021-05-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='likeby',
            new_name='like_by',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='by_user',
            new_name='post_by',
        ),
    ]
