# Generated by Django 3.2.2 on 2021-05-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
