# Generated by Django 3.2.2 on 2021-05-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_auto_20210522_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='view',
            new_name='views',
        ),
    ]
