# Generated by Django 3.2.2 on 2021-05-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_rename_view_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='no_comment',
        ),
    ]
